In [2]:
import numpy as np

# Creating Numpy Array

In [79]:
a1= np.arange(10,)
a2= np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)

In [81]:
# ndim - tells 
a1.ndim

1

In [83]:
# shape 
print(a3.shape)
a3 

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [85]:
# size 
a2.size

12

In [87]:
# itemsize
a1.itemsize # int32 - 4bit , int64 - 8bit

4

In [89]:
# dtype - tell what types of data types it is 
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatype 

In [109]:
# astype - 
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Array Operations 

In [145]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [147]:
# Scalar Operations 
# Arithematic 
a2 + a2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [151]:
# Relational 
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

# Array Functions 

In [217]:
import numpy as np 

# Step 1: Create a 3x3 matrix with random float values between 0 and 1
a1 = np.random.random((3,3))

# Step 2: Multiply all values by 100 to scale them
a1 = a1 * 100

# Optional: Round values if needed
a1 = np.round(a1)

a1


array([[53., 29., 83.],
       [85.,  9., 78.],
       [ 8., 35., 37.]])

In [225]:
# max/min/sum/prod
# 0 -> Col and 1 -> Row
np.prod(a1,axis=0)

array([ 36040.,   9135., 239538.])

In [229]:
# Mean/Median/Mode
np.var(a1,axis=0)

array([997.55555556, 123.55555556, 424.66666667])

In [231]:
# trignometric functions 
np.sin(a1)

array([[ 0.39592515, -0.66363388,  0.96836446],
       [-0.17607562,  0.41211849,  0.51397846],
       [ 0.98935825, -0.42818267, -0.64353813]])

In [237]:
# dot products
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [239]:
# log and Exponents 
np.log(a1)

array([[3.97029191, 3.36729583, 4.41884061],
       [4.44265126, 2.19722458, 4.35670883],
       [2.07944154, 3.55534806, 3.61091791]])

In [254]:
# round/floor/cell
np.floor(np.random.random((2,3))*100)

array([[77., 99., 92.],
       [86., 73., 68.]])

# Indexing and slicing 

In [38]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a2 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a2[1,0]

4

In [51]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
a3[1,1,0]

6

In [55]:
# Slicing 
print(a1)
a1[2:5]

[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4])

In [57]:
print(a2)
a2[0,:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 1, 2, 3])

In [59]:
a2[:,2]

array([ 2,  6, 10])

In [61]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [63]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [65]:
a2[1,::3]

array([4, 7])

In [67]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [69]:
# Second wala 2D array 
a3[1] 
# First and Second 2D array
a3[::2] 
a3[0,1,:] 
# Second wale Middle column 
a3[1,:,1]
#Last Elements : 22, 23, 24, 25
a3[2,1:,1:]
# Elements : 0,2 18 20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [82]:
a1
for i in a1: 
    print(i)

0
1
2
3
4
5
6
7
8
9


In [84]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [86]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [94]:
# Loop for each item 
for i in np.nditer(a3): # a3 ko 1D mey convert kiya aur one by one print kiya/ wrok same with n-dimension 
    print(i) 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping 

In [109]:
# when result dikjae woh temperorily hai aur when result nahi dikhe woh permanent hai - python 

In [111]:
# reshape

In [113]:
# Transpose 
np.transpose(a2)
a2.T # Short Form of Above 

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [115]:
# ravel
a2.ravel() # convert into 1D array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking 

In [133]:
# horizontal splitting 
a4 = np.arange(12).reshape(3,4) # shape should be same 
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [135]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [137]:
# Vertical stacking 
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting 

In [145]:
# horizontal splitting and divide it into two same size array 
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [159]:
# vertical splitting 
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [163]:
np.vsplit(a5,1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]